### PR TITLE
Changing authentication to TOKEN

### PR DESCRIPTION
**Pull request by luizjr**
I carried out the tests, with the modifications I made, we will no longer need to enter a username and password, just a TOKEN which is easier to configure than trying to open the container and insert the validation code, in addition to the fact that the Token is less sensitive/readable what username and password.

### CODE REVIEW

**Comment by Soren90** [comment]
Oh nice! The added support for tokens now?

I'll do some tests and merge in a day or so.

**Comment by luizjr** [comment]
> Oh nice! The added support for tokens now?
> 
> I'll do some tests and merge in a day or so.

Yes.  I tested it here today and it worked.  the best part is not having to put steamguard on every time you restart the server.

**Comment by Soren90** [comment]
> > Oh nice! The added support for tokens now?
> > I'll do some tests and merge in a day or so.
> 
> Yes. I tested it here today and it worked. the best part is not having to put steamguard on every time you restart the server.

Yeah. That is way better. The reason I didn't implement the token was that it wasn't available when I created the image. These tokens is how you would normally do it in CSGO as well.

The pull request does include other stuff (like the GitHub actions) and I would like to make sure that I don't break the container for current users (need to support both account and tokens for a while), so I cannot accept the pull request in the current state. But I can fix it myself when I have time.

I really appreciate your contribution! I'll look into these changes when I have some extra time.

**Comment by Soren90** [comment]
Hi again.

Thanks for your contribution! I really appreciate that!

As there was a lot of other stuff added to the commit other than just the TOKEN changes, I've added the code to the code base manually. 

Feel free to open more pull requests if you've found some other improvements. But please make sure to only include the things that needs to be changed.

**Comment by luizjr** [comment]
> Hi again.
> 
> Thanks for your contribution! I really appreciate that!
> 
> As there was a lot of other stuff added to the commit other than just the TOKEN changes, I've added the code to the code base manually.
> 
> Feel free to open more pull requests if you've found some other improvements. But please make sure to only include the things that needs to be changed.

Dude, your line for installing docker is not aligned with the Docker documentation.
I just improved the readme.md, the issue with the .github folder I agree that it shouldn't even be there.

**Comment by luizjr** [comment]
The name of the TOKEN Variable was also much more obvious for anyone operating Docker and placing this variable to upload the container.

**Comment by Soren90** [comment]
> > Hi again.
> > Thanks for your contribution! I really appreciate that!
> > As there was a lot of other stuff added to the commit other than just the TOKEN changes, I've added the code to the code base manually.
> > Feel free to open more pull requests if you've found some other improvements. But please make sure to only include the things that needs to be changed.
> 
> Dude, your line for installing docker is not aligned with the Docker documentation. I just improved the readme.md, the issue with the .github folder I agree that it shouldn't even be there.

Yes. I saw that you improved the README.md, but using the script is easier and it works on all distros, so I think it makes sense to use that one, as people who knows docker well, most likely knows how to do it specifically for their distro
It's also in the documentation: https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

> The name of the TOKEN Variable was also much more obvious for anyone operating Docker and placing this variable to upload the container.

I don't like to use generic names like TOKEN. Especially considering the fact that workshop content also needs an auth-key (at least that was required for csgo.), so I want to make sure that the variables are as descriptive and self-explanatory as possible.

**Comment by luizjr** [comment]
All good!

**Comment by Soren90** [comment]
> All good!

Great! Thanks again. Please feel free to send a pull request any time!

**Pull request closed without merging**
